---
# Basic template for FMX Prac:

title: "Question 1: Systematic AI Fund"
subtitle: "Question 1: Systematic AI Fund"

documentclass: "elsarticle"

Thesis_FP: FALSE

# --------- Front Page

AddTitle: TRUE
Author1: "Jan-Hendrik Pretorius" 
Ref1: "Stellenbosch University" 
Email1: "20713479\\@sun.ac.za" 

# ----- Manage headers and footers:
BottomRFooter: "\\footnotesize Page \\thepage"
addtoprule: TRUE
addfootrule: TRUE               

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE

# --------- Line numbers
linenumbers: FALSE

# ---------- References settings:
bibliography: Tex/ref.bib       
csl: Tex/harvard-stellenbosch-university.csl

# ---------- General:
RemovePreprintSubmittedTo: TRUE  
Journal: "Financial Econometrics 871"
toc: FALSE                       
numbersections: TRUE             
fontsize: 11pt                  
linestretch: 1.2                
link-citations: TRUE            

### Adding additional latex packages:

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
  Insert abstract if necessary.
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

    #   Housekeeping
rm(list = ls())
options(scipen = 999)
path <- "/Users/janhendrikpretorius/Library/CloudStorage/OneDrive-StellenboschUniversity/01-Masters-2023/02 Financial Econometrics/20713479-FMX-Prac/"

    #   Get external scripts
source(paste0(path, "UTILITIES/libraries.R")) #   Load libraries
source(paste0(path, "UTILITIES/aesthetics.R")) #  Get plot themes
source(paste0(path, "UTILITIES/fee_converter.R")) #  Get plot themes

    #   Load Data

file <- "ASISA_Rets.rds"
ASISA <- read_rds(paste0(path, "DATA/", file))

file <- "Capped_SWIX.rds"
BM <- read_rds(paste0(path, "DATA/", file))

file <- "AI_Max_Fund.rds"
AI <- read_rds(paste0(path, "DATA/", file))

```

<!-- ############################## -->

<!-- # Start of Question: -->

<!-- ############################## -->

```{r data_operations}

set.seed(123321)
sample_size = 4

# Filter ASISA for actively managed funds
ASISA_filtered <- ASISA %>%
  filter(Index == "No") %>%
  select(-Index, -FoF)

# Get average returns for active funds
ASISA_mean <- ASISA_filtered %>%
  group_by(date) %>%
  summarise(Returns = mean(Returns, na.rm = TRUE)) %>% 
  mutate(Fund = "Active Avg") %>%
  mutate(Returns = fee_converter(Returns, 0.01))

# Sample 4 random active funds from ASISA
ASISA_prepared <- ASISA_filtered %>%
  distinct(Fund) %>%
  sample_n(sample_size) %>%
  inner_join(ASISA_filtered, by = "Fund") %>%
  mutate(Returns = fee_converter(Returns, 0.01))

# Preparing AI dataframe
AI_prepared <- AI %>%
  rename(Returns = AI_Fund) %>%
  mutate(Fund = "AI Implementer")

# Preparing BM dataframe
BM_prepared <- BM %>%
  select(-Tickers) %>%
  mutate(Fund = "Benchmark")

# Merging all dataframes
Rets_long <- bind_rows(AI_prepared, BM_prepared, ASISA_prepared, ASISA_mean)


# Converting to wide format
Rets_wide <- Rets_long %>%
  spread(key = Fund, value = Returns)

#   Calculate cumulative returns
Rets_long_cum <- Rets_long %>%
  filter(date >= as.Date("2014-02-28")) %>%
  group_by(Fund) %>%
  mutate(Cumulative_Returns = cumprod(1 + Returns)) %>%
  ungroup()

#   Calculate 3 year rolling returns
Rets_rolling <- 
Rets_long %>% group_by(Fund) %>% 
# Epic sorcery:
mutate(RollRets = RcppRoll::roll_prod(1 + Returns, 36, fill = NA, 
    align = "right")^(12/36) - 1) %>% 
group_by(date) %>% filter(any(!is.na(RollRets))) %>% 
ungroup()

#   Comparing Funds against the Benchmark

# Prepare BM_all
BM_all <- BM_prepared %>%
  select(-Fund) %>%
  rename(Benchmark = Returns)

# Prepare ASISA_all
ASISA_all <- ASISA_prepared %>%
  mutate(Fund = "Actively Managed")

# Merge dataframes
merge_AI <- left_join(AI_prepared, BM_all, by = 'date')
merge_ASISA <- left_join(ASISA_all, BM_all, by = 'date')

Funds_all <- bind_rows(merge_AI, merge_ASISA)
```


```{r inspect}

# Basic data inspection
tablestats <-
  Rets_wide %>% tbl_xts() %>% 
  table.Stats(., ci = 0.95, digits = 3)
print(tablestats[,1:7])

```


```{r boxplot}

# Calculate the median for the AI fund
ai_median <- median(Rets_wide$`AI Implementer`, na.rm = TRUE)

boxplot <- Rets_long %>% 
    ggplot(aes(x = Fund, y = Returns, fill = Fund)) +
      geom_boxplot(color = "black") +
      geom_hline(yintercept = ai_median, linetype = "dashed", color = "black", size = 1) +
      scale_fill_manual(values = palette) +
      labs(title = "Comparison of Returns* Across Funds",
           subtitle = "Horizontal dashed line represents median of AI Implementer returns,\nwhich is 0.02.",
           caption = "*After fees (Management fee is 100bps)",
           x = "Fund",
           y = "Returns",
           fill = "Fund") +
      th +
      theme(legend.position = "none",
            axis.text.x = element_text(angle=90, hjust = 1))
ggsave("Figures/boxplot.png", plot = boxplot)

```



```{r scatplot}

calculate_performance <- function(data, fund_name) {
    # Calculate the number of instances of outperformance
    outperform <- data %>%
        filter(Fund == fund_name & Returns > Benchmark) %>%
        nrow()

    # Calculate the number of instances of underperformance
    underperform <- data %>%
        filter(Fund == fund_name & Returns < Benchmark) %>%
        nrow()

    # Calculate the percentage of outperformance
    perform_percentage <- outperform / (outperform + underperform) * 100

    # Return the formatted percentage as a string
    rounded_performance <- round(perform_percentage, 2)
    return(paste0(rounded_performance, "%"))
}


performance_active <- calculate_performance(Funds_all, "Actively Managed")
performance_ai <- calculate_performance(Funds_all, "AI Implementer")

# Create the scatter plot
scatplot <- Funds_all %>% 
    ggplot(aes(x = Benchmark, y = Returns, color = Fund)) +
        # Shading triangles
        geom_ribbon(aes(ymin = -Inf, ymax = Benchmark), fill = "#C93D44", alpha = 0.2) +
        geom_ribbon(aes(ymin = Benchmark, ymax = Inf), fill = "#75A21B", alpha = 0.2) +
        geom_point(size = 1) +  # Add points
        geom_abline(slope = 1, intercept = 0, linetype = "dashed") +  # 45-degree line
        geom_smooth(method = "lm", formula = y ~ x, aes(group = Fund), se = FALSE) +  # Ab-lines
        scale_color_manual(values = palette) +
        labs(title = "Comparison of Fund Returns* vs. Benchmark",
             subtitle = "Dashed line represents a 45ยบ-line, indicating a 1-to-1 correlation between\nfund returns and benchmark. Actively managed funds outperform the\nbenchmark 44.57% of the time, while AI Implementer outperforms\n57.43% of the time.",
             caption = "*After fees (Management fee is 100bps)",
             x = "Benchmark Returns",
             y = "Fund Returns",
             color = "Fund Type") + th +
    annotate("text", x = -0.08, y = 0.15, label = "Outperform Benchmark", hjust = 0.5, family= "Palatino") +
    annotate("text", x = 0.08, y = -0.15, label = "Underperform Benchmark", hjust = 0.5, family= "Palatino")



# Add labels to the plot
scatplot <- scatplot 

# Here, x_position, y_position_1, and y_position_2 are the coordinates where you want to place the labels.
# You need to adjust these based on your plot's scale and layout.

# Now, you can view or save your plot
print(scatplot)

ggsave("Figures/scatplot.png", plot = scatplot)

```


```{r cumplot}
cumplot <- Rets_long_cum %>% 
    #filter(Fund == "Active Avg" | Fund == "AI Implementer" | Fund == "Benchmark") %>% 
    ggplot(aes(x = date, y = Cumulative_Returns, color = Fund)) +
      geom_line(size = 1) +
      scale_color_manual(values = palette) +
      labs(title = "Growth of $1 Invested* Over Time",
           caption = "*After fees (Management fee is 100bps)",
           x = "Date",
           y = "Cumulative Returns",
           color = "Fund") +
      scale_y_continuous(labels = scales::dollar_format(prefix = "$", suffix = "")) +
      th

ggsave("Figures/cumplot.png", plot = cumplot)

```

```{r rollplot}
rollplot <- Rets_rolling %>% 
    #filter(Fund == "Active Avg" | Fund == "AI Implementer" | Fund == "Benchmark") %>% 
    ggplot(aes(x = date, y = RollRets, color = Fund)) +
      geom_line(size = 0.8) +
      scale_color_manual(values = palette) +
      labs(title = "3-Year Rolling Annual Returns* for Selected Funds",
           caption = "*After fees (Management fee is 100bps)",
           x = "",
           y = "Rolling 3 year Returns (Ann.)",
           color = "Fund") +
      scale_y_continuous(labels = scales::percent_format(scale = 100)) +
      th

ggsave("Figures/rollplot.png", plot = rollplot)

```
