---
# Basic template for FMX Prac:

title: "Question 1: Analysis of Financial Data"
subtitle: "Question 1: Analysis of Financial Data"

documentclass: "elsarticle"

Thesis_FP: FALSE

# --------- Front Page

AddTitle: TRUE
Author1: "Jan-Hendrik Pretorius" 
Ref1: "Stellenbosch University" 
Email1: "20713479\\@sun.ac.za" 

# ----- Manage headers and footers:
BottomRFooter: "\\footnotesize Page \\thepage"
addtoprule: TRUE
addfootrule: TRUE               

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE

# --------- Line numbers
linenumbers: FALSE

# ---------- References settings:
bibliography: Tex/ref.bib       
csl: Tex/harvard-stellenbosch-university.csl

# ---------- General:
RemovePreprintSubmittedTo: TRUE  
Journal: "Financial Econometrics 871"
toc: FALSE                       
numbersections: TRUE             
fontsize: 11pt                  
linestretch: 1.2                
link-citations: TRUE            

### Adding additional latex packages:

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
  Insert abstract if necessary.
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

    #   Housekeeping
rm(list = ls())
options(scipen = 999)
path <- "/Users/janhendrikpretorius/Library/CloudStorage/OneDrive-StellenboschUniversity/01-Masters-2023/02 Financial Econometrics/20713479-FMX-Prac/"

    #   Get external scripts
source(paste0(path, "UTILITIES/libraries.R")) #   Load libraries
source(paste0(path, "UTILITIES/aesthetics.R")) #  Get plot themes

    #   Load Data
#file <- "TEST-DATA.xlsx"
#df_deaths <- read_xlsx(paste0(path, "DATA/", file))
```

<!-- ############################## -->

<!-- # Start of Question: -->

<!-- ############################## -->


```{r results = 'asis'}

# Set seed for reproducibility
set.seed(123)

# Generating numerical data
numerical_1 <- rnorm(100) # 100 random numbers from a normal distribution
numerical_2 <- rnorm(100)

# Generating categorical data
categories <- sample(c("A", "B", "C", "D", "E", "F", "G"), 100, replace = TRUE)

# Generating boolean data
boolean <- sample(c(TRUE, FALSE), 100, replace = TRUE)

# Combining all into a data frame
hypothetical_data <- data.frame(Numerical_1 = numerical_1, 
                                Numerical_2 = numerical_2, 
                                Category = categories, 
                                Boolean = boolean)

# Viewing the first few rows of the dataset

data <- head(hypothetical_data)
table <- xtable(data, caption = "Long Table Example")
  print.xtable(table,
             tabular.environment = "longtable",
             floating = FALSE,
             table.placement = 'H',
             booktabs = T,
             include.rownames = FALSE,
             comment = FALSE,
             caption.placement = 'top',
             size="\\fontsize{12pt}{13pt}\\selectfont"
             )


```

```{r}

hypothetical_data %>%
  ggplot(aes(x = Numerical_1, y = Numerical_2, color = Category)) +
    geom_point() +
    scale_color_manual(values = palette) +
    th +
    ggtitle("Scatter Plot of Numerical Data")


```

```{r}

hypothetical_data %>% 
  ggplot(aes(x = Category, y = Numerical_1, color = Category)) +
    geom_boxplot() +
    scale_color_manual(values = palette) +
    th +
    ggtitle("Boxplot Grouped by Category")


```


```{r}

hypothetical_data %>% 
  ggplot(aes(x = Category, fill = Boolean)) +
    geom_bar() +
    scale_fill_manual(values = palette)+
    th +
    ggtitle("Bar Plot of Categories")

```


```{r}

hypothetical_data %>% 
  ggplot(aes(x = Numerical_1, fill = Category)) +
    geom_histogram(binwidth = 0.5, color = "black") +
    scale_fill_manual(values = palette) +
    th +
    ggtitle("Histogram of Numerical_1")

```

```{r}

hypothetical_data %>% 
  ggplot(aes(x = Numerical_1, fill = Boolean)) +
    geom_density(alpha = 0.6) +
    scale_fill_manual(values = palette) +
    th +
    ggtitle("Density Plot of Numerical_1")

```

```{r}
hypothetical_data %>% 
  ggplot(aes(x = Numerical_1, y = Numerical_2, color = Category)) +
    geom_point() +
    scale_color_manual(values = palette) +
    facet_wrap(~ Boolean) +
    th +
    ggtitle("Scatter Plots Faceted by Category")

```

